[package]
name = "kdtree-wasm"
version = "0.1.0"
authors = ["Kenan Sulayman <kenan@sly.mn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.50"
kdtree = "0.5.1"
